sudo: required
language: scala
scala:
  - 2.10.6
services:
  - docker

before_install:
  - docker build --build-arg SPARK_VERSION=$SPARK_VERSION -t hydrosphere/mist:$TRAVIS_BRANCH-$SPARK_VERSION .
  - docker run hydrosphere/mist:$TRAVIS_BRANCH-$SPARK_VERSION /bin/sh -c "/usr/share/spark/bin/spark-shell --version"
script:
  - /usr/share/spark/bin/spark-shell --version

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#     docker push hydrosphere/mist:$TRAVIS_BRANCH-$SPARK_VERSION;
#     fi

env:
  global:
    secure: f+Kg5LkG5fBsJ5/V7dOxWGMUeWPBU8vUNDk0HsytNtm9mTnospTiFykoxiXbKNhVlmfhmAsyseIcKIrFwSoz/6rlJXiHYdTeH/DSoCa/JLDLMn/7zJp8v6lwer2KEpc+cnUiG5TMR1QmGJ2yVrw1DrwUqs9hBrWNP1bmr1wXGgrde56fnFXKy6YlToUWqtqHn0lMYaV/gBH7jdCdC4Q3n1FlAe9a8x7Lecy3sm489Fpyf6MuekdrulmW15YXJ71XAiEwGA24zxqOd5Pp2Vcyg2UNVtTyjyqlybhX65Ov/hzup44xjdyEFW0u7jt7AdIKTXBrHVvfoLg5c52Jltr+yhJA37zgntWRIA1pRWxJXOpfL5zaICLSVovS0J4xfdPOgK6o4kCVGBNQdy/jeKyFtPAE2SFjDQ4pCeSBUJ3uk0w2MEnyTluZHg2vQtjKXDVsLNxD6sr6UPUURgMm8d7BR8tqVzCUU5kwdR1WQVzkNEmurXv0Zuohjc1NK8f9Qwqd7DlEAtdtpSVg1F9V5qzOeEGq0aYy6Uu2R8WEN8SiZITdVgL0LZQo12kOPqoSJLNERx0KFNIaqBtsuqnZirdCPgF7FeZou5iN5sxVSX7OL8/AnuhV/W8R/V0n2K90rXY6OXfOwl4ojVxc7uoavHmLzhmfDVUcQv22AXwicT3DQRU=
  matrix:
    - SPARK_VERSION=1.5.2
    - SPARK_VERSION=1.6.2
    - SPARK_VERSION=2.0.0

branches:
  only:
  - docker
